### ISSUE TITLE
Model.create() does not have the option to set only `overwrite`

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#87]
`catModel.create(cat, { overwrite: true } );` -> Complains that it requires return

**Comment by hardyscc** [comment]
@MickL Please add `return: "document"` like following
```ts
catModel.create(cat, { overwrite: true, return: "document" } );
```

**Comment by MickL** [comment]
Why that is not a required value by Dynamoose, just in your interfaces

**Comment by hardyscc** [comment]
@MickL please check this out from dynamoose

https://github.com/dynamoose/dynamoose/blob/27326613aa391f0223ef05d2e95c21e33d630a27/lib/Model/index.ts#L828  

which is exactly the same as here :

```ts
  get( key: Key, settings: ModelGetSettings & { return: 'document' }): Promise<Data>;
```
The reason is that it is required by the Typescript type inference to correctly choose the right interface

**Comment by MickL** [comment]
Hm then maybe that interface is wrong? I am not using `return: 'document'` with `@ts-ignore` and it works as expected. I dont think it is or should be required.

**Comment by hardyscc** [comment]
@MickL yes it shouldn't be required, you may ask @fishcharlie about this :)

**Comment by MickL** [comment]
I opened an issue: https://github.com/dynamoose/dynamoose/issues/912
